stages:
  - deploy

sync_to_github:
  stage: deploy
  only:
    - to_git
  script:
    - git clone --branch to_git "${CI_REPOSITORY_URL}" temp-repo
    - cd temp-repo
    - git remote add github "https://oauth2:${GITHUB_TOKEN}@github.com/MaxPolychilFax/git_test.git"
    - git fetch github main || echo "GitHub branch doesn't exist yet"  # Проверяем существование ветки на GitHub
    - git push --force github to_git:main
    #- git diff --quiet github/main..to_git || git push github to_git:main  # Пушим только если есть различия